# Generated by Django 4.0.4 on 2022-06-03 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_grid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='product_grid.products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='categories',
            field=models.ManyToManyField(related_name='product_cate', to='product_grid.categories'),
        ),
    ]
